AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Parameters:
  BasicExecutionRoleName:
    Default: lambda-basic-execution
    Description: Name of an existing execution role for this function
    Type: String
  Environment:
    Default: sandbox
    Description: Analogous to a Medistrano stage/environment name
    Type: String
  Project:
    Description: Analogous to a Medistrano project name
    Type: String
Resources:
  helloworldpython3:
    Properties:
      CodeUri: s3://sam-packages-2c6f24a1/helloworld/2e86b15a1bea1eb7071edede856bc5bc
      Description: A starter AWS Lambda function.
      FunctionName:
        Fn::Sub: ${Project}-${Environment}-HelloFunction
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/${BasicExecutionRoleName}
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31

